import type { Metadata } from "next";
import { Pinyon_Script } from "next/font/google";
import "./globals.css";
import Header from "./components/shared/Header";
import Footer from "./components/shared/Footer";
import { PageProvider } from "./context/PageContext";

const pinyonScript = Pinyon_Script({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pinyon-script",
});

export const metadata: Metadata = {
  title: "Phantacia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pinyonScript.variable}>
      <body className="flex flex-col min-h-screen">
        <PageProvider>
          <Header />
          {children}
          <Footer />
        </PageProvider>
      </body>
    </html>
  );
}
